baseURL = "https://frabatx.com/"
languageCode = "ita"
title = "Frabatx"

[menu]

 [[menu.main]]
    name = "skills"
    url = "/skills"
    weight = 1

 [[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "blog"
    url = "/blog/"
    weight = 3
 
  [[menu.main]]
    name = "contact"
    url = "/contact"
    weight = 4